# This is a basic workflow to help you get started with Actions
name: HTML Validator

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  html-validator:    
    name: HTML5 Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HTML5 Validator
        # You may pin to the exact commit or the version.
        # uses: Cyb3r-Jak3/html5validator-action@5232895eb5636721a71cf451eaeb5c4629d2cf02
        uses: Cyb3r-Jak3/html5validator-action@v0.4.2
        with:
          css: true
          log_level: INFO
          format: text
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.log
      - uses: chabad360/htmlproofer@v1.1
        with:
        # The directory to scan
          directory: ./
